name: Deploy .NET 8 API to Codespaces

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the API
        run: dotnet build --configuration Release --no-restore

      - name: Publish to Codespaces
        run: |
          dotnet publish -c Release -o publish
          mkdir -p ~/.codespaces/.persistedshare/published-api
          cp -r publish/* ~/.codespaces/.persistedshare/published-api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Start .NET 8 API in Codespaces
        run: |
          dotnet ~/.codespaces/.persistedshare/published-api/YourAppName.dll
        env:
          ASPNETCORE_ENVIRONMENT: Production
          PORT: 8080
          CODESPACES: true
