name: Deploy .NET 8 API to Codespaces

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/Genisys.Farmers.Api/Genisys.Farmers.Api.csproj

      - name: Build the API
        run: dotnet build src/Genisys.Farmers.Api/Genisys.Farmers.Api.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish API
        run: |
          dotnet publish src/Genisys.Farmers.Api/Genisys.Farmers.Api.csproj -c Release -o ./publish
          echo "Listing files in publish directory:"
          ls -al ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Start .NET 8 API
        run: |
          echo "Verifying contents of the publish directory:"
          ls -al home/runner/work/FarmersApi/FarmersApi/publish/
          dotnet home/runner/work/FarmersApi/FarmersApi/publish/Genisys.Farmers.Api.dll
        env:
          ASPNETCORE_ENVIRONMENT: Production
          PORT: 8080
          CODESPACES: true
